### ISSUE TITLE
"& was unexpected at this time" error when compiling with cmd terminal

### ISSUE THREAD

**Issue by kentonlam** [DafnyVSCode/ide-vscode#22]
The [current implementation](https://github.com/DafnyVSCode/ide-vscode/blob/d09d03388f7b3a650aafea5ee089f78ed7894f59/src/serverRequests/compile.ts#L66) of the compile command prepends a `&` to the command line on Windows. This is needed so Powershell interprets the line as a program to execute but causes problems for the older cmd terminal. cmd only permits & between commands.

Some possible solutions:
- Add configuration option to override this prefix behaviour.
- Somehow detect whether the current shell is powershell or cmd.

This is exactly the same issue as https://github.com/DafnyVSCode/Dafny-VSCode/issues/48.

**Comment by camrein** [comment]
Thank you for your bug report. As you suggested, I've made the terminal command prefix configurable with the setting `dafny.terminalCommandPrefix`.
