### ISSUE TITLE
Syntax errors are reported as "verified"

### ISSUE THREAD

**Issue by fpoli** [DafnyVSCode/ide-vscode#32]
When there is a syntax error in the program, for example a file containing just "asd", the IDE shows ":+1: Verified" but it also reports a syntax error.

**Comment by camrein** [comment]
Thank you for the report. I have adapted Dafny's language server to not expose documents with syntactic and/or semantic errors as verified.
As I've seen from another issue that you're using the "onsave" setting. What is your preference there? Would you like to immediately switch to "Not Verified" upon any change or just when you actively save?

**Comment by fpoli** [comment]
I don't have a strong preference, but switching to "Not Verified" as soon as I edit the document sounds good to me.

**Comment by camrein** [comment]
I have updated the extension accordingly. Please mind that this change requires the changes of the language server in the linked PR. Therefore, it might take some time until we release an update.
