### ISSUE TITLE
Extension not recognizing newly created .dfy files

### ISSUE THREAD

**Issue by fpoli** [DafnyVSCode/ide-vscode#33]
When I create a new `.dfy` file from vscode, I cannot immediately verify it. The extension doesn't seem to recognize that it's a Dafny file. I have to close and reopen the IDE; then it works.

**Comment by camrein** [comment]
I've tried reproducing this error. On Windows and OSX newly created files with a `.dfy` extension are immediately recognized by the extension, including syntax highlighting and code completion/navigation/etc.
Could it be that you have also installed the legacy extension in VSCode so it could interfere with it? Or any other extension that might be misbehaving? Maybe it's worth giving a clean installation a try.

**Comment by fpoli** [comment]
Thanks for trying. I tried again and I actually can no longer reproduce this. Maybe disabling other extensions was indeed enough.
